AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  Table:
    PrimaryKey:
      Name: greeting
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnits: 2
      WriteCapacityUnits: 2
    Type: AWS::Serverless::SimpleTable
  helloworldpython3:
    Properties:
      CodeUri: s3://kl-tbu-sam-chatbot-translator/ad4e7b19c6c9d8c612a060bf2943cabc
      Description: A starter AWS Lambda function.
      Environment:
        Variables:
          REGION_NAME:
            Ref: AWS::Region
          TABLE_NAME:
            Ref: Table
      Events:
        klStUdemyHelloWorldSAMAPI:
          Properties:
            Method: GET
            Path: /hello
          Type: Api
      Handler: app.lambda_handler
      MemorySize: 128
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
