AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  helloworldpython3:
    Properties:
      CodeUri: s3://kl-tbu-sam-chatbot-translator/a1c6af21d9484f6087e6d6b5296b892e
      Description: A starter AWS Lambda function.
      Handler: app.lambda_handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
