AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function.
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  helloworldpython3:
    Properties:
      CodeUri: s3://kl-tbu-sam-chatbot-translator/7625bbea7b1bd98bd22892c6fcf3e075
      Description: A starter AWS Lambda function.
      Events:
        klStUdemyHelloWorldSAMAPI:
          Properties:
            Method: GET
            Path: /hello
          Type: Api
      Handler: app.lambda_handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
